[package]
name = "BinomialDistributionGraphDrawingRewrite"
version = "0.1.0"
edition = "2021"

[dependencies]
plotly = { version = "0.12", features = ["kaleido", "kaleido_download"] }
rand = "0.8.5"
rand_distr = "0.4.3"
